# Create a deployment for the config-server containers
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wb3-k8s-config-server
  labels:
    app: config-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: wb3-k8s-config-server
        image: k8springcloud/config-server
        imagePullPolicy: Always
        env:

        # Configure container to work with the service mesh (Linkerd)
        - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: http_proxy
                  value: $(NODE_NAME):4140

        # Application & Spring Cloud configurations
        - name: APP_NAME
          value: "WB3-K8s-ConfigServer"
        - name: CONFIG_SERVER_ENCRYPT_ENABLED
          value: "true"
        - name: CONFIG_SERVER_GIT_URI
          value: "https://github.com/k8s-spring-cloud/1-Configuration"
        - name: ENCRYPT_KEY
          value: "TheVerySecretKey"
        - name: SERVER_PORT
          value: "0"
        - name: SERVICE_DISCOVERY_ENABLED
          value: "true"
        - name: SERVICE_DISCOVERY_HOST
          value: "http://service-discovery"
        - name: SERVICE_DISCOVERY_PORT
          value: "8500"
        ports:
        - containerPort: 80
          name: transport
          protocol: TCP